export const CHANGE_SELECTED_KEY = 'CHANGE_SELECTED_KEY';
export const CHANGE_CHECKED_KEYS = 'CHANGE_CHECKED_KEYS';
export const SELECT_FILES = 'SELECT_FILES';
export const SET_SELECTED_FILENAME = 'SET_SELECTED_FILENAME';
